name: CI/CD Azure Python App

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Récupère ton code
    - name: Checkout code
      uses: actions/checkout@v3

    # 2️⃣ Configure Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    # 3️⃣ Installe les dépendances
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4️⃣ Étape de test (facultative)
    - name: Run tests
      run: echo "No tests yet!"

    # 5️⃣ Connexion à Azure via le Service Principal JSON
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # 6️⃣ Déploiement sur ton App Service
    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        slot-name: 'production'
